name: "CARBONOZ SolarAutopilot - AI Charging"
version: "1.0.1"
slug: "carbonoz_solarautopilot"
description: "Live solar dashboard and AI-powered battery charging optimization for Home Assistant with Tibber integration"
url: "https://github.com/CARBONOZ-RENEWABLES/solarautopilot-addon"
arch:
  - aarch64
  - amd64
  - armv7
init: false
apparmor: false
panel_icon: "mdi:solar-power"
panel_title: "Carbonoz SolarAutopilot"
panel_admin: false
map:
  - share:rw
ingress: true
ingress_port: 6789
ingress_stream: true
ports:
  "3001/tcp": 3001
  "6789/tcp": 6789
  "8000/tcp": 8000
  "8086/tcp": 8086
image: "ghcr.io/carbonoz-renewables/solarautopilot:latest"
legacy: true
startup: application
options:
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic_prefix: "solarautopilot"
  battery_number: "1"
  inverter_number: "1"
  clientId: ""
  clientSecret: ""
schema:
  mqtt_username: str
  mqtt_password: str
  mqtt_topic_prefix: str
  battery_number: str
  inverter_number: str
  clientId: str
  clientSecret: str