name: "CARBONOZ SolarAutopilot - AI Charging (Test)"
version: "1.0.1-test"
slug: "carbonoz_solarautopilot_test"
description: "Test version of CARBONOZ SolarAutopilot"
url: "https://github.com/CARBONOZ-RENEWABLES/carbonoz_solarautopilotV1"
image: "ghcr.io/carbonoz-renewables/carbonoz-solarautopilotv1:{arch}-latest"
map:
  - share:rw
  - ssl
  - /data:/data
  - /data/backup:/data/backup
ports:
  "3001/tcp": 3001
  "6789/tcp": 6789
  "8000/tcp": 8000
  "8086/tcp": 8086
ports_description:
  3001/tcp: "Web interface (optional)"
  6789/tcp: "Main application"
  8000/tcp: "WebSocket"
  8086/tcp: "InfluxDB"
panel_icon: "mdi:solar-power"
panel_title: "Carbonoz SolarAutopilot Test"
ingress: true
ingress_port: 6789
ingress_stream: true
startup: application
init: false
memory_limit: 512mb
options:
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic_prefix: ""
  battery_number: 1
  inverter_number: 1
  clientId: ""
  clientSecret: ""
schema:
  mqtt_username: "str?"
  mqtt_password: "password?"
  mqtt_topic_prefix: "str"
  battery_number: "int(1,)"
  inverter_number: "int(1,)"
  clientId: "str"
  clientSecret: "password"
panel: true