apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    database: 'home_assistant'
    user: 'admin'
    secureJsonData:
      password: 'adminpassword'
    jsonData:
      httpMode: GET
      timeInterval: "1s" 
